#!/usr/bin/perl

use strict;
use warnings;

use LWP::UserAgent;
use HTTP::Cookies;
use Date::Calc;
use Net::SMTP::SSL;
use File::Basename;

# ------------------------- constants

my $file_threads = dirname(0) . '/threads.dat';
my $file_cookies = dirname(0) . '/cookies.dat';

# ------------------------- read old threads.dat

my %old_threads;

unless (-e $file_threads) {
	open (FP, '>' . $file_threads);
	close(FP);
}

open (FP, '<' . $file_threads);
while (my $line = <FP>) {
#	chomp $line;
#	my ($k, @v) = split /\t/mis, $line;
#	%old_threads{$k} = @v;
	print $line;
}
close (FP);

# ------------------------- get new data

my $cookie_jar = HTTP::Cookies->new(
	file => $file_cookies,
	autosave => 1,
);

my $ua = LWP::UserAgent->new;
$ua->cookie_jar($cookie_jar);
$ua->agent('Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.121 Safari/535.2');
push @{ $ua->requests_redirectable }, 'POST';

$ua->add_handler(request_prepare => sub {
	my($request, $ua, $h) = @_;
#	print $request->as_string(), "\n";
});

$ua->add_handler(response_header => sub {
	my($response, $ua, $h) = @_;
#	print $response->as_string(), "\n";
});

my $r = $ua->get('http://www.forum.stosowana.pl/search.php?&sr=topics&search_id=unread');

die '-ERR(1)- ', $r->status_line
	unless $r->is_success;

if ($r->content =~ m/Zaloguj<\/title>/mis) {
	my $sid = '';
	if ($r->content =~ m/name="sid"\s+value="([^"]+)"/mis) {
		$sid = $1;
	}

	$r = $ua->post('http://www.forum.stosowana.pl/ucp.php?mode=login', [
		'username' => 'michalrus',
		'password' => '4A?%*}",i1=3w]>dFixU',
		'autologin' => '',
		'redirect' => 'search.php?&sr=topics&search_id=unread',
		'sid' => '',
		'login' => 'Zaloguj'
		]);

	die '-ERR(2)- ', $r->status_line
		unless $r->is_success;

	$r = $ua->get('http://www.forum.stosowana.pl/search.php?&sr=topics&search_id=unread');

	die '-ERR(3)- ', $r->status_line
		unless $r->is_success;
}

my @tbl = split /<tr\s+valign="middle">/mis, $r->content;
shift @tbl;

# ------------------------- parse <tr/> rows and generate new threads

my %new_threads;

foreach my $row (@tbl) {
	$row =~ s/<\/tr>.*//mis;

	my $thread_id = '';
	my $last_post_id = '';
	my $forum = '';
	my $title = '';
	my $last_author = '';
	my $last_date = '';

	if ($row =~ m/\.\/viewtopic\.php\?f=\d+&amp;t=(\d+)&amp;p=(\d+)#p\d+/mis) {
		$thread_id = $1;
		$last_post_id = $2;
	}

	if ($row =~ m/w <a href="\.\/viewforum\.php\?f=\d+">([^<]+)<\/a>/mis) {
		$forum = $1;
	}

	if ($row =~ m/class="topictitle">([^<]+)<\/a>/mis) {
		$title = $1;
	}

	if ($row =~ m/<p class="topicdetails"><a href="\.\/memberlist\.php\?mode=viewprofile&amp;u=\d+"[^>]*>([^<]+)<\/a>/mis) {
		$last_author = $1;
	}

	if ($row =~ m/<p class="topicdetails">[^ ]+ (\d\d [^ ]+, \d\d\d\d \d\d:\d\d)<\/p>/mis) {
		$last_date = $1;
	}

	if (1 > 0) {
		print "thread_id:    " . $thread_id . "\n";
		print "last_post_id: " . $last_post_id . "\n";
		print "forum:        " . $forum . "\n";
		print "title:        " . $title . "\n";
		print "last_author:  " . $last_author . "\n";
		print "last_date:    " . $last_date . "\n";
		print "\n";
	}
}

# ------------------------- save new threads.dat

open (FP, '>' . $file_threads);
while (my ($k, @v) = each (%new_threads)) {
	print FP $k . "\t" . join("\t", @v) . "\n";
}
close (FP);

